// World Bank Open Data API Client & Curated Indicator Catalog
// Free, CORS-friendly, zero-backend REST client for 29,000+ development indicators.

import { COUNTRIES, getCountry } from '../data/countries.js';

// Recognized country ISO3 set
const VALID_ISOS = new Set(COUNTRIES.map(c => c.iso3));

/**
 * Curated catalog of high-frequency, impactful World Bank & UN indicators.
 */
export const CURATED_WB_INDICATORS = [
  // 1. Economy & Trade
  {
    id: 'NY.GDP.PCAP.CD',
    name: 'GDP per Capita (Current US$)',
    short: 'GDP/Cap',
    domain: 'economy',
    unit: 'US$',
    polarity: 1,
    source: 'World Bank National Accounts',
    desc: 'Gross domestic product divided by midyear population in current U.S. dollars.'
  },
  {
    id: 'NY.GDP.PCAP.PP.CD',
    name: 'GDP per Capita, PPP (Current Intl $)',
    short: 'GDP (PPP)',
    domain: 'economy',
    unit: 'Intl $',
    polarity: 1,
    source: 'World Bank ICP',
    desc: 'GDP per capita converted to international dollars using purchasing power parity rates.'
  },
  {
    id: 'FP.CPI.TOTL.ZG',
    name: 'Inflation, Consumer Prices (Annual %)',
    short: 'Inflation',
    domain: 'economy',
    unit: '%',
    polarity: -1,
    source: 'IMF International Financial Statistics',
    desc: 'Annual percentage change in the cost to the average consumer of acquiring a basket of goods.'
  },
  {
    id: 'GC.TAX.TOTL.GD.ZS',
    name: 'Tax Revenue (% of GDP)',
    short: 'Tax/GDP',
    domain: 'economy',
    unit: '% GDP',
    polarity: 1,
    source: 'IMF Government Finance Statistics',
    desc: 'Compulsory transfers to central government for public purposes as share of GDP.'
  },
  {
    id: 'BX.KLT.DINV.WD.GD.ZS',
    name: 'Foreign Direct Investment, Net Inflows (% of GDP)',
    short: 'FDI Inflow',
    domain: 'economy',
    unit: '% GDP',
    polarity: 1,
    source: 'World Bank / UNCTAD',
    desc: 'Net inflows of investment to acquire a lasting management interest in an enterprise.'
  },
  {
    id: 'NE.EXP.GNFS.ZS',
    name: 'Exports of Goods and Services (% of GDP)',
    short: 'Exports/GDP',
    domain: 'economy',
    unit: '% GDP',
    polarity: 1,
    source: 'World Bank National Accounts',
    desc: 'Value of all goods and market services provided to the rest of the world.'
  },
  {
    id: 'NE.IMP.GNFS.ZS',
    name: 'Imports of Goods and Services (% of GDP)',
    short: 'Imports/GDP',
    domain: 'economy',
    unit: '% GDP',
    polarity: 1,
    source: 'World Bank National Accounts',
    desc: 'Value of all goods and market services received from the rest of the world.'
  },
  {
    id: 'GC.DOD.TOTL.GD.ZS',
    name: 'Central Government Debt, Total (% of GDP)',
    short: 'Gov Debt',
    domain: 'economy',
    unit: '% GDP',
    polarity: -1,
    source: 'IMF / World Bank',
    desc: 'Gross total stock of government direct liabilities as percentage of GDP.'
  },
  {
    id: 'SL.UEM.TOTL.ZS',
    name: 'Unemployment, Total (% of Total Labor Force)',
    short: 'Unemployment',
    domain: 'economy',
    unit: '% Labor',
    polarity: -1,
    source: 'International Labour Organization (ILO)',
    desc: 'Share of labor force that is without work but available and seeking employment.'
  },
  {
    id: 'SL.UEM.1524.ZS',
    name: 'Youth Unemployment Rate (% of Labor Force 15-24)',
    short: 'Youth Unemp',
    domain: 'economy',
    unit: '% Youth',
    polarity: -1,
    source: 'ILO Estimates',
    desc: 'Share of the labor force ages 15-24 without work but actively seeking employment.'
  },
  {
    id: 'SI.POV.GINI',
    name: 'Gini Index of Income Inequality (0-100)',
    short: 'Gini Index',
    domain: 'economy',
    unit: 'Index',
    polarity: -1,
    source: 'World Bank Poverty Database',
    desc: 'Measures extent to which distribution of income among individuals deviates from equity.'
  },
  {
    id: 'SI.POV.DDAY',
    name: 'Poverty Headcount Ratio at $2.15 a Day (2017 PPP)',
    short: 'Extreme Pov',
    domain: 'economy',
    unit: '% Pop',
    polarity: -1,
    source: 'World Bank Poverty Portal',
    desc: 'Percentage of population living on less than $2.15 a day at 2017 international prices.'
  },

  // 2. Climate, Energy & Environment
  {
    id: 'EG.ELC.RNEW.ZS',
    name: 'Renewable Electricity Output (% of Total Electricity)',
    short: 'Renewable Elec',
    domain: 'environment',
    unit: '% Output',
    polarity: 1,
    source: 'IEA / World Bank',
    desc: 'Share of total electricity generated by renewable sources (hydro, solar, wind, geothermal, bio).'
  },
  {
    id: 'EG.FEC.RNEW.ZS',
    name: 'Renewable Energy Consumption (% of Total Final Energy)',
    short: 'Renewable En',
    domain: 'environment',
    unit: '% Energy',
    polarity: 1,
    source: 'IEA Statistics',
    desc: 'Share of renewable energy in overall total final energy consumption.'
  },
  {
    id: 'EN.ATM.CO2E.PC',
    name: 'CO2 Emissions (Metric Tons per Capita)',
    short: 'CO2/Cap',
    domain: 'environment',
    unit: 't/Cap',
    polarity: -1,
    source: 'Global Carbon Project / CDIAC',
    desc: 'Carbon dioxide emissions stemming from burning fossil fuels and cement manufacture.'
  },
  {
    id: 'EN.ATM.METH.KT.CE',
    name: 'Methane Emissions (Thousand Metric Tons CO2 Equivalent)',
    short: 'Methane',
    domain: 'environment',
    unit: 'kt CO2e',
    polarity: -1,
    source: 'EDGAR / World Bank',
    desc: 'Total methane emissions from agricultural, industrial, and waste processes.'
  },
  {
    id: 'EN.ATM.PM25.MC.M3',
    name: 'PM2.5 Air Pollution, Mean Annual Exposure (mcg/m3)',
    short: 'Air PM2.5',
    domain: 'environment',
    unit: '?g/m?',
    polarity: -1,
    source: 'Brauer et al. / IHME',
    desc: 'Population-weighted exposure to ambient fine particulate matter under 2.5 microns.'
  },
  {
    id: 'AG.LND.FRST.ZS',
    name: 'Forest Area (% of Total Land Area)',
    short: 'Forest Land',
    domain: 'environment',
    unit: '% Land',
    polarity: 1,
    source: 'Food and Agriculture Organization (FAO)',
    desc: 'Land spanning more than 0.5 hectares with trees higher than 5 meters and canopy over 10%.'
  },
  {
    id: 'ER.H2O.FWTL.ZS',
    name: 'Annual Freshwater Withdrawals (% of Internal Resources)',
    short: 'Water Stress',
    domain: 'environment',
    unit: '% Resource',
    polarity: -1,
    source: 'FAO AQUASTAT',
    desc: 'Total freshwater withdrawal as percentage of total renewable water resources.'
  },
  {
    id: 'ER.PTD.TOTL.ZS',
    name: 'Terrestrial and Marine Protected Areas (% of Total Area)',
    short: 'Protected Area',
    domain: 'environment',
    unit: '% Area',
    polarity: 1,
    source: 'UNEP-WCMC World Database on Protected Areas',
    desc: 'Totally or partially protected areas of at least 1,000 hectares designated by authorities.'
  },

  // 3. Health & Wellbeing
  {
    id: 'SP.DYN.LE00.IN',
    name: 'Life Expectancy at Birth, Total (Years)',
    short: 'Life Exp',
    domain: 'health',
    unit: 'Years',
    polarity: 1,
    source: 'UN Population Division',
    desc: 'Number of years a newborn infant would live if prevailing mortality patterns stay constant.'
  },
  {
    id: 'SH.MED.BEDS.ZS',
    name: 'Hospital Beds (per 1,000 People)',
    short: 'Hosp Beds',
    domain: 'health',
    unit: 'Beds/1k',
    polarity: 1,
    source: 'World Health Organization (WHO)',
    desc: 'Inpatient hospital beds available in public, private, general, and specialized hospitals.'
  },
  {
    id: 'SH.MED.PHYS.ZS',
    name: 'Physicians / Doctors (per 1,000 People)',
    short: 'Doctors/1k',
    domain: 'health',
    unit: 'MD/1k',
    polarity: 1,
    source: 'WHO Global Health Workforce Statistics',
    desc: 'Generalist and specialist medical practitioners per 1,000 population.'
  },
  {
    id: 'SH.MED.NUMW.P3',
    name: 'Nurses and Midwives (per 1,000 People)',
    short: 'Nurses/1k',
    domain: 'health',
    unit: 'RN/1k',
    polarity: 1,
    source: 'WHO Global Health Observatory',
    desc: 'Practicing professional nurses, associate nurses, and midwives per 1,000 population.'
  },
  {
    id: 'SH.XPD.CHEX.GD.ZS',
    name: 'Current Health Expenditure (% of GDP)',
    short: 'Health Exp',
    domain: 'health',
    unit: '% GDP',
    polarity: 1,
    source: 'WHO Global Health Expenditure Database',
    desc: 'Total healthcare goods and services consumed during each year as percentage of GDP.'
  },
  {
    id: 'SP.DYN.IMRT.IN',
    name: 'Infant Mortality Rate (per 1,000 Live Births)',
    short: 'Infant Mort',
    domain: 'health',
    unit: 'per 1k',
    polarity: -1,
    source: 'UN Inter-agency Group for Child Mortality Estimation',
    desc: 'Number of infants dying before reaching one year of age per 1,000 live births.'
  },
  {
    id: 'SH.STA.MMRT',
    name: 'Maternal Mortality Ratio (per 100,000 Live Births)',
    short: 'Maternal Mort',
    domain: 'health',
    unit: 'per 100k',
    polarity: -1,
    source: 'WHO, UNICEF, UNFPA, World Bank',
    desc: 'Number of women who die from pregnancy-related causes during pregnancy or within 42 days.'
  },
  {
    id: 'SH.STA.SUIC.P5',
    name: 'Suicide Mortality Rate (per 100,000 Population)',
    short: 'Suicide Rate',
    domain: 'health',
    unit: 'per 100k',
    polarity: -1,
    source: 'WHO Global Health Estimates',
    desc: 'Number of suicide deaths in a year per 100,000 population.'
  },
  {
    id: 'SH.IMM.MEAS',
    name: 'Immunization, Measles (% of Children Ages 12-23 Months)',
    short: 'Measles Vax',
    domain: 'health',
    unit: '% Vax',
    polarity: 1,
    source: 'WHO and UNICEF Estimates',
    desc: 'Percentage of children ages 12-23 months who received measles vaccination.'
  },

  // 4. Education & Human Capital
  {
    id: 'SE.ADT.LITR.ZS',
    name: 'Adult Literacy Rate, Total (% of People Ages 15+)',
    short: 'Literacy Rate',
    domain: 'education',
    unit: '% Pop',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Percentage of population ages 15 and older who can read and write with understanding.'
  },
  {
    id: 'SE.PRM.ENRR',
    name: 'School Enrollment, Primary (% Gross)',
    short: 'Primary Enroll',
    domain: 'education',
    unit: '% Gross',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Total enrollment in primary education, regardless of age, expressed as percentage of official age group.'
  },
  {
    id: 'SE.SEC.ENRR',
    name: 'School Enrollment, Secondary (% Gross)',
    short: 'Secondary Enroll',
    domain: 'education',
    unit: '% Gross',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Total enrollment in secondary education, regardless of age, as share of official secondary age population.'
  },
  {
    id: 'SE.TER.ENRR',
    name: 'School Enrollment, Tertiary / Higher Education (% Gross)',
    short: 'Tertiary Enroll',
    domain: 'education',
    unit: '% Gross',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Total enrollment in university/tertiary education as share of 5-year post-secondary age group.'
  },
  {
    id: 'SE.XPD.TOTL.GD.ZS',
    name: 'Government Expenditure on Education, Total (% of GDP)',
    short: 'Educ Exp/GDP',
    domain: 'education',
    unit: '% GDP',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Total general government expenditure on education (current and capital) expressed as % of GDP.'
  },
  {
    id: 'SE.PRM.ENRL.FE.ZS',
    name: 'Primary Education, Female Enrollment (% of Total)',
    short: 'Female Primary',
    domain: 'education',
    unit: '% Female',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Female students enrolled in primary school as percentage of total primary enrollment.'
  },

  // 5. Technology, Infrastructure & Innovation
  {
    id: 'IT.NET.USER.ZS',
    name: 'Individuals Using the Internet (% of Population)',
    short: 'Internet Users',
    domain: 'technology',
    unit: '% Pop',
    polarity: 1,
    source: 'International Telecommunication Union (ITU)',
    desc: 'Percentage of population who have used the internet from any location via any device in the last 3 months.'
  },
  {
    id: 'IT.CEL.SETS.P2',
    name: 'Mobile Cellular Subscriptions (per 100 People)',
    short: 'Mobile Subs',
    domain: 'technology',
    unit: 'per 100',
    polarity: 1,
    source: 'ITU World Telecommunication Database',
    desc: 'Subscriptions to a public mobile telephone service providing access to the PSTN.'
  },
  {
    id: 'EG.ELC.ACCS.ZS',
    name: 'Access to Electricity (% of Total Population)',
    short: 'Electricity Access',
    domain: 'technology',
    unit: '% Pop',
    polarity: 1,
    source: 'World Bank Tracking SDG 7',
    desc: 'Percentage of population with access to electricity from grid or off-grid generation.'
  },
  {
    id: 'TX.VAL.TECH.MF.ZS',
    name: 'High-Technology Exports (% of Manufactured Exports)',
    short: 'High-Tech Exp',
    domain: 'technology',
    unit: '% Mfg Exp',
    polarity: 1,
    source: 'UN COMTRADE Database',
    desc: 'Products with high R&D intensity: aerospace, computers, pharma, scientific instruments, electrical.'
  },
  {
    id: 'GB.XPD.RSDV.GD.ZS',
    name: 'Research and Development Expenditure (% of GDP)',
    short: 'R&D/GDP',
    domain: 'technology',
    unit: '% GDP',
    polarity: 1,
    source: 'UNESCO Institute for Statistics',
    desc: 'Gross domestic expenditure on scientific research and experimental development as share of GDP.'
  },
  {
    id: 'IP.PAT.RESD',
    name: 'Patent Applications, Residents (Count)',
    short: 'Resident Patents',
    domain: 'technology',
    unit: 'Patents',
    polarity: 1,
    source: 'World Intellectual Property Organization (WIPO)',
    desc: 'Patent applications filed through the patent office for exclusive rights for an invention.'
  },
  {
    id: 'IS.AIR.PSGR',
    name: 'Air Transport, Passengers Carried (Total Count)',
    short: 'Air Passengers',
    domain: 'technology',
    unit: 'Passengers',
    polarity: 1,
    source: 'International Civil Aviation Organization (ICAO)',
    desc: 'Domestic and international aircraft passengers of air carriers registered in the country.'
  },

  // 6. Governance, Society & Gender
  {
    id: 'SG.GEN.PARL.ZS',
    name: 'Proportion of Seats Held by Women in National Parliaments (%)',
    short: 'Women in Parl',
    domain: 'governance',
    unit: '% Seats',
    polarity: 1,
    source: 'Inter-Parliamentary Union (IPU)',
    desc: 'Percentage of parliamentary seats in single or lower chambers occupied by women.'
  },
  {
    id: 'SL.TLF.CACT.FE.ZS',
    name: 'Labor Force Participation Rate, Female (% of Female Pop 15+)',
    short: 'Female Labor',
    domain: 'governance',
    unit: '% Female',
    polarity: 1,
    source: 'International Labour Organization',
    desc: 'Proportion of female population ages 15 and older that is economically active.'
  },
  {
    id: 'VC.IHR.PSRC.P5',
    name: 'Intentional Homicides (per 100,000 People)',
    short: 'Homicide Rate',
    domain: 'governance',
    unit: 'per 100k',
    polarity: -1,
    source: 'UNODC / World Bank',
    desc: 'Unlawful death purposefully inflicted on a person by another person per 100,000 population.'
  },

  // 7. Demographics & Urbanization
  {
    id: 'SP.URB.TOTL.IN.ZS',
    name: 'Urban Population (% of Total Population)',
    short: 'Urban Pop',
    domain: 'demographics',
    unit: '% Urban',
    polarity: 1,
    source: 'UN Population Division',
    desc: 'People living in urban areas as defined by national statistical offices.'
  },
  {
    id: 'SP.DYN.TFRT.IN',
    name: 'Fertility Rate, Total (Births per Woman)',
    short: 'Fertility Rate',
    domain: 'demographics',
    unit: 'Births/W',
    polarity: 1,
    source: 'UN Population Division',
    desc: 'Number of children that would be born to a woman if she were to live to the end of her childbearing years.'
  },
  {
    id: 'SP.POP.DPND',
    name: 'Age Dependency Ratio (% of Working-Age Population)',
    short: 'Dependency Ratio',
    domain: 'demographics',
    unit: '% Ratio',
    polarity: -1,
    source: 'World Bank Staff Estimates',
    desc: 'Ratio of dependents (people younger than 15 or older than 64) to the working-age population.'
  },
  {
    id: 'EN.POP.DNST',
    name: 'Population Density (People per Sq. Km of Land Area)',
    short: 'Pop Density',
    domain: 'demographics',
    unit: 'People/km?',
    polarity: 1,
    source: 'Food and Agriculture Organization / World Bank',
    desc: 'Midyear population divided by land area in square kilometers.'
  },

  // 8. Agriculture & Food Security
  {
    id: 'AG.LND.ARBL.ZS',
    name: 'Arable Land (% of Total Land Area)',
    short: 'Arable Land',
    domain: 'food',
    unit: '% Land',
    polarity: 1,
    source: 'Food and Agriculture Organization (FAO)',
    desc: 'Land under temporary agricultural crops, meadows for mowing or pasture, market gardens, fallow land.'
  },
  {
    id: 'AG.PRD.FOOD.XD',
    name: 'Food Production Index (2014-2016 = 100)',
    short: 'Food Prod Idx',
    domain: 'food',
    unit: 'Index',
    polarity: 1,
    source: 'Food and Agriculture Organization (FAO)',
    desc: 'Covers food crops that are considered edible and contain nutrients (cereals, livestock, oils, roots).'
  }
];

/**
 * Searches the curated catalog and optionally queries live World Bank indicator catalog API.
 * @param {string} query - Keyword search
 * @param {string} domainFilter - Domain filter or 'all'
 * @returns {Array<Object>} List of matched indicator definitions
 */
export function searchCuratedWorldBankCatalog(query = '', domainFilter = 'all') {
  const q = query.trim().toLowerCase();

  return CURATED_WB_INDICATORS.filter(item => {
    const matchesDomain = domainFilter === 'all' || item.domain === domainFilter;
    if (!matchesDomain) return false;

    if (!q) return true;

    return (
      item.id.toLowerCase().includes(q) ||
      item.name.toLowerCase().includes(q) ||
      item.short.toLowerCase().includes(q) ||
      (item.desc && item.desc.toLowerCase().includes(q)) ||
      (item.source && item.source.toLowerCase().includes(q))
    );
  });
}

/**
 * Performs a live keyword search directly against the World Bank 29,000+ indicator database.
 * @param {string} query
 * @returns {Promise<Array<Object>>}
 */
export async function searchLiveWorldBankApi(query) {
  if (!query || query.trim().length < 2) return [];

  const q = encodeURIComponent(query.trim());
  const url = `https://api.worldbank.org/v2/indicator?format=json&q=${q}&per_page=50`;

  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const json = await response.json();

    if (!json || !Array.isArray(json) || json.length < 2 || !Array.isArray(json[1])) {
      return [];
    }

    return json[1].map(raw => {
      // Guess domain from sourceOrganization or topic
      let domain = 'economy';
      const nameLower = (raw.name || '').toLowerCase();
      if (nameLower.includes('health') || nameLower.includes('mortality') || nameLower.includes('hospital') || nameLower.includes('disease')) domain = 'health';
      else if (nameLower.includes('emission') || nameLower.includes('energy') || nameLower.includes('forest') || nameLower.includes('water') || nameLower.includes('climate')) domain = 'environment';
      else if (nameLower.includes('school') || nameLower.includes('education') || nameLower.includes('literacy')) domain = 'education';
      else if (nameLower.includes('internet') || nameLower.includes('patent') || nameLower.includes('technology') || nameLower.includes('research')) domain = 'technology';
      else if (nameLower.includes('women') || nameLower.includes('law') || nameLower.includes('corruption') || nameLower.includes('homicide') || nameLower.includes('parliament')) domain = 'governance';
      else if (nameLower.includes('population') || nameLower.includes('urban') || nameLower.includes('fertility')) domain = 'demographics';
      else if (nameLower.includes('food') || nameLower.includes('agriculture') || nameLower.includes('crop')) domain = 'food';

      // Guess polarity
      const isNegative = nameLower.includes('mortality') || nameLower.includes('poverty') || nameLower.includes('homicide') || nameLower.includes('unemployment') || nameLower.includes('pollution') || nameLower.includes('emission') || nameLower.includes('debt') || nameLower.includes('inflation') || nameLower.includes('suicide');

      return {
        id: raw.id,
        name: raw.name,
        short: raw.name.length > 20 ? raw.name.substring(0, 18) + '?' : raw.name,
        domain,
        unit: raw.unit || 'Index',
        polarity: isNegative ? -1 : 1,
        source: raw.sourceOrganization || 'World Bank Open Data',
        desc: raw.sourceNote || 'World Bank Open Data development metric.',
        isLiveApiResult: true
      };
    });
  } catch (err) {
    console.warn('[WorldBankAPI] Live indicator search fallback failed:', err);
    return [];
  }
}

/**
 * Fetches indicator country data across all countries using mrv=5 (most recent 5 observation years fallback).
 * Harmonizes to our 183 ISO-3166-1 alpha-3 recognized countries.
 * @param {string} indicatorId - e.g. "SH.MED.BEDS.ZS"
 * @param {Object} metaOverride - optional custom metadata
 * @returns {Promise<Object>} Formatted indicator object ready for INDICATORS dictionary
 */
export async function fetchWorldBankIndicatorData(indicatorId, metaOverride = {}) {
  // Query with mrv=5 & per_page=1500 to capture latest non-null observation for every country
  const url = `https://api.worldbank.org/v2/country/all/indicator/${indicatorId}?format=json&mrv=5&per_page=1500`;

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`World Bank API returned HTTP ${response.status}`);
  }

  const json = await response.json();
  if (!json || !Array.isArray(json) || json.length < 2 || !Array.isArray(json[1])) {
    throw new Error(`No country observations found for indicator ${indicatorId}`);
  }

  const rawRows = json[1];
  const countryData = {};
  const countryYears = {};
  let totalValid = 0;
  let minYear = 9999;
  let maxYear = 0;

  // Iterate in chronological/natural order: pick the most recent valid year for each country
  rawRows.forEach(row => {
    const iso = row.countryiso3code;
    const val = row.value;
    const year = parseInt(row.date, 10);

    if (iso && VALID_ISOS.has(iso) && val !== null && val !== undefined && !isNaN(val)) {
      // Because WB returns newest year first per country, if we haven't seen this ISO or year is newer:
      if (countryData[iso] === undefined || (year && year > (countryYears[iso] || 0))) {
        countryData[iso] = typeof val === 'number' ? Math.round(val * 1000) / 1000 : parseFloat(val);
        countryYears[iso] = year || 2023;
        if (year) {
          if (year < minYear) minYear = year;
          if (year > maxYear) maxYear = year;
        }
        totalValid++;
      }
    }
  });

  const matchedCount = Object.keys(countryData).length;
  if (matchedCount < 5) {
    throw new Error(`Only ${matchedCount} recognized countries had data for indicator ${indicatorId}.`);
  }

  // Look up catalog metadata or fallback
  const catalogMeta = CURATED_WB_INDICATORS.find(i => i.id === indicatorId) || {};
  const firstRow = rawRows[0] || {};
  const indicatorTitle = metaOverride.name || catalogMeta.name || (firstRow.indicator ? firstRow.indicator.value : indicatorId);

  const finalYearRange = maxYear > 0 ? (minYear === maxYear ? `${maxYear}` : `${minYear}?${maxYear}`) : 'Recent';

  return {
    id: indicatorId,
    name: indicatorTitle,
    short: metaOverride.short || catalogMeta.short || indicatorTitle.substring(0, 16),
    domain: metaOverride.domain || catalogMeta.domain || 'economy',
    polarity: metaOverride.polarity !== undefined ? metaOverride.polarity : (catalogMeta.polarity !== undefined ? catalogMeta.polarity : 1),
    unit: metaOverride.unit || catalogMeta.unit || 'Value',
    source: catalogMeta.source || 'World Bank Open Data API',
    year: finalYearRange,
    desc: catalogMeta.desc || `World Bank international development dataset with ${matchedCount} matched sovereign nations (${finalYearRange}).`,
    data: countryData,
    matchedCount,
    isExternal: true
  };
}